/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import model.Customer;
import service.CustomerService;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.Connection;
import conexion.CreateConnection;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author arten
 */
public class FrmCustomer extends javax.swing.JFrame {
    
    private DefaultTableModel model;
    private CustomerService service = new CustomerService();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCustomer.class.getName());
    CreateConnection conexion = new CreateConnection();
    /**
     * Creates new form Cliente
     */
    public FrmCustomer() {
        initComponents();
        
        model = new DefaultTableModel(
                new String[]{
                        "ID", "Nombre", "Apellido",
                        "Correo", "Dirección", "Teléfono"
                },
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // la tabla es solo de lectura
            }
        };
        
        jtCliente.setModel(model);
        jtCliente.getSelectionModel().addListSelectionListener(e -> {

        if (!e.getValueIsAdjusting()) {
            cargarSeleccion();
        }
        cargarSeleccion();
});
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtCliente = new javax.swing.JTable();
        txtcode = new javax.swing.JTextField();
        btnQuerry = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jlcode = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        jlLastName = new javax.swing.JLabel();
        jlAddress = new javax.swing.JLabel();
        jlgmail = new javax.swing.JLabel();
        txtgmail = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        jlphone = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        BtReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtCliente);

        txtcode.addActionListener(this::txtcodeActionPerformed);

        btnQuerry.setText("Consultar");
        btnQuerry.addActionListener(this::btnQuerryActionPerformed);

        txtName.addActionListener(this::txtNameActionPerformed);

        jlcode.setText("Codigo");

        jlName.setText("Nombre");

        jlLastName.setText("Apellido");

        jlAddress.setText("Direccion");

        jlgmail.setText("Correo");

        jlphone.setText("Telefono");

        btnCreate.setText("Guardar");
        btnCreate.addActionListener(this::btnCreateActionPerformed);

        btnUpdate.setText("Modificar");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClean.setText("Limpiar");
        btnClean.addActionListener(this::btnCleanActionPerformed);

        BtReport.setText("Reporte");
        BtReport.addActionListener(this::BtReportActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlcode, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlgmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlphone, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgmail, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(jlLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtReport)
                    .addComponent(btnQuerry)
                    .addComponent(btnCreate)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClean))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlgmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlphone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnQuerry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClean)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodeActionPerformed

    private void btnQuerryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuerryActionPerformed
        // TODO add your handling code here:
        loadCustomer();
        
    }//GEN-LAST:event_btnQuerryActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        agregarCliente();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        modificarCliente();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         eliminarCliente();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void BtReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtReportActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn=conexion.getConnection();
            String reportPath = "C:\\Users\\arten\\OneDrive\\Escritorio\\UMG\\PrograII\\Netbeans\\com.umg.api\\src\\main\\java\\com\\mycompany\\com\\umg\\ui\\Cliente.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, cn);
            JasperViewer.viewReport(jp);

            
   
        
     
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    
    }//GEN-LAST:event_BtReportActionPerformed

//-------------------------------------------METODOS -------------------------------------------    
    //GET
    public void loadCustomer(){
         try {
        List<Customer> clientes = service.getCustomers();

        model.setRowCount(0); // limpia la tabla

        for (Customer c : clientes) {
            model.addRow(new Object[]{
                    c.getId(),
                    c.getNombre(),
                    c.getApellido(),
                    c.getCorreo(),
                    c.getDireccion(),
                    c.getTelefono()
            });
        }

    } catch (Exception e) {
             JOptionPane.showMessageDialog(
                this,
                "Error al cargar clientes: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }
    
    //POST
    private void agregarCliente() {

    try {
        Customer c = new Customer();
        c.setNombre(jlName.getText());
        c.setApellido(jlLastName.getText());
        c.setCorreo(jlgmail.getText());
        c.setDireccion(jlAddress.getText());
        c.setTelefono(jlphone.getText());
        c.setStatus(true);

        // No se asigna c.setIngreso(): lo hace CustomerService automáticamente

        service.createCustomer(c);

        loadCustomer();
        limpiarFormulario();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "Error al crear cliente: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}
    //Limpiar
    private void limpiarFormulario() {
    txtcode.setText("");
    txtName.setText("");
    txtLastName.setText("");
    txtgmail.setText("");
    txtAddress.setText("");
    txtphone.setText("");
    jtCliente.clearSelection();
}

private void cargarSeleccion() {
    int viewRow = jtCliente.getSelectedRow();

    if (viewRow == -1) {
        return; // Ninguna fila seleccionada
    }

    int modelRow = jtCliente.convertRowIndexToModel(viewRow);

    Object idObject = model.getValueAt(modelRow, 0);

    int id;
    if (idObject instanceof Number) {
        id = ((Number) idObject).intValue();
    } else {
        id = Integer.parseInt(String.valueOf(idObject));
    }

    // Asignar a los JTextFields en lugar de los JLabels:
    txtcode.setText(String.valueOf(id));
    txtName.setText(String.valueOf(model.getValueAt(modelRow, 1)));
    txtLastName.setText(String.valueOf(model.getValueAt(modelRow, 2)));
    txtgmail.setText(String.valueOf(model.getValueAt(modelRow, 3)));
    txtAddress.setText(String.valueOf(model.getValueAt(modelRow, 4)));
    txtphone.setText(String.valueOf(model.getValueAt(modelRow, 5)));
}
//UPDATE
private void modificarCliente() {

    try {
        int id = Integer.parseInt(jlcode.getText());

        Customer c = new Customer();
        c.setId(id);
        c.setNombre(jlName.getText());
        c.setApellido(jlLastName.getText());
        c.setCorreo(jlgmail.getText());
        c.setDireccion(jlAddress.getText());
        c.setTelefono(jlphone.getText());
        c.setStatus(true);

        service.updateCustomer(id, c);

        loadCustomer();
        limpiarFormulario();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "Error al modificar cliente: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}
//DELETE
private void eliminarCliente() {

    int viewRow = jtCliente.getSelectedRow();

    if (viewRow == -1) {
        JOptionPane.showMessageDialog(
                this,
                "Selecciona un cliente primero.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int modelRow = jtCliente.convertRowIndexToModel(viewRow);
    int id = ((Number) model.getValueAt(modelRow, 0)).intValue();
    String nombre = String.valueOf(model.getValueAt(modelRow, 1));

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Desea eliminar al cliente?\n\nID: " + id + "\nNombre: " + nombre,
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        service.deleteCustomer(id);
        loadCustomer();
        limpiarFormulario();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "Error al eliminar cliente: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCustomer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtReport;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnQuerry;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlAddress;
    private javax.swing.JLabel jlLastName;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlcode;
    private javax.swing.JLabel jlgmail;
    private javax.swing.JLabel jlphone;
    private javax.swing.JTable jtCliente;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtgmail;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
